#!/bin/sh
HISTFILE=$ZDOTDIR/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

# path
export PATH="$HOME/.local/bin":$PATH
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH" # For GNU Make

# man page
export MANPAGER='nvim +Man!' # Man page in nvim
export MANWIDTH=999

# global enviroment variables
export EDITOR="nvim"
export TERMINAL="kitty"

PATH="${PATH}:/opt/gcc-arm-none-eabi/bin"
PATH="${PATH}:/opt/JLink_Linux"
PATH="${PATH}:/opt/nrf-command-line-tools/bin"
PATH="${PATH}:/opt/clangd/bin"
export PATH

LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/JLink_Linux"
export LD_LIBRARY_PATH

GNU_INSTALL_ROOT="/opt/gcc-arm-none-eabi"
export GNU_INSTALL_ROOT
